template: true
valuesFilePath: ./values.yml

resources:
  {{ range $i, $e := until 500 }}
  - name: monitor_cron_trigger_a{{$i}}
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *' # Every 5 minutes
      branches:
        include: test
  {{ end }}

pipelines:
  - name: testcron
    steps:
      {{ range $i, $e := until 500 }}
      - name: basic_a{{$i}}
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: monitor_cron_trigger_a{{$i}}
        execution:
          onExecute:
            - echo hi
      {{ end }}
